[project]
name = "py-cstgs"
version = "0.1.5"
description = "Counting and Sampling Triangles from a Graph Stream"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cstgs>=0.1.5",
    "polars>=1.31.0",
    "pydantic>=2.11.7",
    "tqdm>=4.67.1",
]
