[project]
name = "py-cstgs"
version = "0.1.3"
description = "Counting and Sampling Triangles from a Graph Stream"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cstgs>=0.1.0",
    "polars>=1.31.0",
    "pydantic>=2.11.7",
]
